-- Migration to add "Çocuklu Aileler İçin Fethiye" article
-- Generated by Gemini Agent

-- 1. Insert the article
INSERT INTO articles (
    title,
    slug,
    content,
    cover_image_url,
    location,
    meta_description,
    is_published,
    published_at,
    created_at,
    updated_at
) VALUES (
    'Çocuklu Aileler İçin Fethiye: Sığ Deniz, Rüzgarsız Koylar ve Güvenli Tatil Rehberi',
    'cocuklu-aileler-icin-fethiye-sig-deniz-rehberi',
    '<h1>Çocuklu Aileler İçin Fethiye: Sığ Deniz, Rüzgarsız Koylar ve Güvenli Tatil Rehberi</h1>

<p>Çocukla deniz tatili bazen “dinlenme” değil, resmen gözetleme kulesi görevi: göz hep suda, kulak hep “anneee/babaa”da. O yüzden ailelerin aklındaki sorular da çok net: “Deniz hemen derinleşiyor mu?”, “Dalga var mı?”, “Zemin kum mu çakıl mı?”, “Gölge var mı?”</p>

<p>Fethiye bu konuda avantajlı bir yer; çünkü körfez yapısı ve kapalı koyları sayesinde bazı noktaları gerçekten “doğal çocuk havuzu” gibi. Ama her plaj aynı değil. Örneğin Ölüdeniz’in daha açık kısımlarında deniz bazı günler hızlı derinleşebilir veya rüzgârla dalga oluşabilir. Yani mesele “Fethiye mi?” değil; Fethiye’nin hangi koyu + hangi saat?</p>

<p>Bu rehberde, otel/işletme adı vermeden; çocukların güvenle suya girebileceği, senin de “5 dakika kafamı kaldırmadan oturayım” diyebileceğin sığ ve sakin seçenekleri anlatıyorum. En sona da “çocukla tatil kurtaran” pratik ipuçlarını ve SSS’yi koydum.</p>

<div class="bg-blue-50 p-6 rounded-lg my-8">
    <h2 class="text-xl font-bold mb-4 text-blue-800">30 Saniyelik Özet (Okumaya Üşenen Ebeveyn Modu)</h2>
    <ul class="space-y-2">
        <li>🌊 <strong>Sığ ve dalgasız su:</strong> En güvenli yaklaşım lagün/kapalı koy mantığı.</li>
        <li>🎯 <strong>Hedefin:</strong> (1) Yavaş derinleşen giriş + (2) Rüzgâr almayan koy + (3) Gölge + (4) WC/duş erişimi.</li>
        <li>⏰ <strong>Zamanlama:</strong> Sabah erken (09:00-11:00) gidince tatil 2 kat kolaylaşıyor.</li>
        <li>🚗 <strong>Uzak plajlar:</strong> Dönüş saatlerini iyi planla.</li>
    </ul>
</div>

<h2>Çocuklu Aileler İçin “Güvenli Deniz” Kriterleri</h2>

<p>Bu kısmı bir kere kafaya yaz, Fethiye’de (ve her yerde) işin kolaylaşır:</p>

<ul class="list-disc pl-6 space-y-2 mb-6">
    <li><strong>Derinleşme hızı:</strong> İlk 10–20 metrede bile bel hizasına geliyorsa küçük çocuk için stres artar.</li>
    <li><strong>Dalga/rüzgâr:</strong> Rüzgâr alan açık kısımlar öğleden sonra dalga yapabilir.</li>
    <li><strong>Zemin:</strong> İnce kum çocukla en rahat; iri çakıl bazı çocukları huzursuz eder (diz/ayak acısı).</li>
    <li><strong>Gölge:</strong> 11:00–16:00 arası gölge “lüks” değil, ihtiyaç.</li>
    <li><strong>Giriş-çıkış kolaylığı:</strong> Bebek/çocuk çantasıyla merdiven, taşlık patika, dik yokuş işi zorlaştırır.</li>
    <li><strong>Tuvalet/duş/soyuna alanı:</strong> Çocuklu tatilde “olsa iyi olur” değil, bazen “olmazsa olmaz”.</li>
</ul>

<hr class="my-8" />

<h2>Bölüm 1 — Erişimi Kolay, Çocuk Dostu Seçenekler</h2>

<h3>1) Doğal Bir Çocuk Havuzu: Ölüdeniz Lagün Bölgesi</h3>

<p>Ölüdeniz denince akla gelen o cam gibi durgun su hissi, lagün mantığının ürünü. Burası, çocuklu ailelerin “ilk günden moral depoladığı” yerlerden.</p>

<div class="my-6">
    <img src="YOUR_IMAGE_URL_HERE/oludeniz-lagun-calm.webp" alt="Ölüdeniz Lagün Bölgesi - Sakin ve Sığ Deniz" class="w-full h-auto rounded-lg shadow-md" />
</div>

<ul class="list-disc pl-6 space-y-2">
    <li><strong>Deniz yapısı:</strong> Su genelde sakindir; dalga çoğu gün minimum olur. Birçok noktada giriş yavaş derinleşir. Dip yapısı bölgeye göre ince kum + yer yer küçük çakıl olabilir.</li>
    <li><strong>Çocuk için artıları:</strong> “Su kaçıyor, dalga çarpıyor” stresi az olur. Çocuk suya alışana kadar kıyıda oyalamak kolaydır.</li>
    <li><strong>Gölge ve konfor:</strong> Bazı bölümlerde ağaçlık alanlar gölge sağlar; bu çocukla tatilde çok değerli.</li>
</ul>

<div class="bg-yellow-50 p-4 border-l-4 border-yellow-400 my-4">
    <strong>⚠️ Gerçekçi Uyarı:</strong> Bu tür korunan alanlarda giriş ücreti olabiliyor ve uygulamalar sezona göre değişebiliyor. Sezonda geç gidersen kalabalık olabilir. En iyi saat: 09:00–10:30 arası.
</div>

<h3>2) Merkeze Yakın, Sakin Koy Hissi: Aksazlar Koyu</h3>

<p>Merkeze yakın olup “çocukla fazla uğraştırmayan” yerler altın değerinde. Aksazlar tarafı da genelde koy hissi verdiği için su daha sakin olabiliyor.</p>

<ul class="list-disc pl-6 space-y-2">
    <li><strong>Deniz yapısı:</strong> Koy yapısı nedeniyle su çoğu zaman daha durgundur. Giriş kısmı birçok gün sığ başlayabilir.</li>
    <li><strong>Çocukla neden rahat?</strong> Ağaçlık alanların suya yakın olduğu yerlerde gölge avantajı büyük. Çocuk bir yandan suyla oynarken sen de güneşle savaşmazsın.</li>
    <li><strong>Konfor notu:</strong> Çocukla denizde en çok aranan şeylerden biri “yakında WC/duş var mı?” sorusu. Bu tip noktalarda genelde bu ihtiyaçları karşılayan düzenli alanlar bulunur.</li>
</ul>

<h3>3) Geniş Alan + Aile Odaklı Düzen: İnlice Plajı</h3>

<p>İnlice tarafı, özellikle kalabalık aileler için “geniş alan” avantajı sunar. Çocukla denizde bazen en büyük mesele su değil; kumsalda hareket alanı.</p>

<ul class="list-disc pl-6 space-y-2">
    <li><strong>Deniz yapısı:</strong> Sabah saatleri genelde daha sakin olur. Öğleden sonra rüzgâr artarsa su hareketlenebilir.</li>
    <li><strong>Neden aileler sever?</strong> Kumsal geniş olduğunda çocuk “kumla oynayayım, koşayım” diye enerjisini atar. Kalabalıkta bile “nefes alanı” bulmak daha kolay olur.</li>
    <li><strong>Taktik:</strong> Sabah deniz → öğlene doğru gölgede mola → öğleden sonra “kısa bir yürüyüş/gezinti” şeklinde plan yaparsan çocuk da sen de yıpranmazsın.</li>
</ul>

<hr class="my-8" />

<h2>Bölüm 2 — Bir Tık Daha Doğa, Bir Tık Daha Plan</h2>

<h3>4) Çam Ormanı + Kapalı Koy Mantığı: Katrancı Koyu Tabiat Parkı</h3>

<p>Katrancı tarafı, doğayla iç içe olmak isteyen ama “temel ihtiyaçlar da olsun” diyen ailelerin sevdiği tarzda bir yer.</p>

<div class="my-6">
    <img src="YOUR_IMAGE_URL_HERE/katranci-bay-nature.webp" alt="Katrancı Koyu - Doğa ile İç İçe" class="w-full h-auto rounded-lg shadow-md" />
</div>

<ul class="list-disc pl-6 space-y-2">
    <li><strong>Deniz yapısı:</strong> Koy mantığı sayesinde birçok gün deniz daha sakin olabilir. Bazı bölümlerde giriş daha yumuşak ve yavaş derinleşebilir.</li>
    <li><strong>Aile açısından büyük artı:</strong> Çam ağaçları ve gölgeli alanlar çocukla tatilde gerçekten hayat kurtarır. Piknik/kamp düzeni olan yerlerde “çocuğu uyuttum, biraz nefes aldım” senaryosu daha mümkün olur.</li>
    <li><strong>Konfor notu:</strong> Market/WC/duş gibi temel imkanlar bulunabiliyor. Girişte bir hızlı kontrol yap.</li>
</ul>

<h3>5) Tekne Turu Seçimi: “Parti” Değil “Aile” Mantığı</h3>

<p>Çocuklar tekneye bayılır ama her tekne turu çocuk için uygun değildir. En büyük fark genelde şudur: Yüksek ses/tempo = yorucu; Sakin tempo = konforlu.</p>

<p><strong>Seçerken soracağın 3 soru:</strong></p>
<ol class="list-decimal pl-6 space-y-2">
    <li>“Müzik seviyesi nasıl?”</li>
    <li>“Duraklar sığ mı, çocukla girilir mi?”</li>
    <li>“Tur kaç saat sürüyor, ara verme düzeni nasıl?”</li>
</ol>

<hr class="my-8" />

<h2>Çocukla Fethiye’yi Kolaylaştıran Pratik İpuçları</h2>

<div class="grid md:grid-cols-2 gap-6 my-6">
    <div class="bg-white p-4 rounded-lg border border-gray-200 shadow-sm">
        <h4 class="font-bold text-lg mb-2">👶 Bebek Arabası mı, Kanguru mu?</h4>
        <p>Düz yürüyüş yolları (sahil bandı) için bebek arabası harika. Taşlı/engebeli yerlerde kanguru ciddi fark yaratır.</p>
    </div>
    <div class="bg-white p-4 rounded-lg border border-gray-200 shadow-sm">
        <h4 class="font-bold text-lg mb-2">🛒 Market ve İhtiyaç</h4>
        <p>Büyük paketleri taşımak yerine “2 günlük yeter” mantığıyla gel, gerisini Fethiye merkezden temin et.</p>
    </div>
    <div class="bg-white p-4 rounded-lg border border-gray-200 shadow-sm">
        <h4 class="font-bold text-lg mb-2">🦟 Akşam Sivrisinek Konusu</h4>
        <p>Akşamüstü çantada mutlaka “bebek/çocuk uyumlu” bir koruyucu bulunsun.</p>
    </div>
    <div class="bg-white p-4 rounded-lg border border-gray-200 shadow-sm">
        <h4 class="font-bold text-lg mb-2">🏥 Sağlık Konusu</h4>
        <p>Konakladığın yerin en yakın sağlık noktasını ilk gün haritada işaretle.</p>
    </div>
</div>

<h3>Çocukla Denize Giriş Zamanı: Saat Seçimi Her Şeyi Değiştirir</h3>

<div class="my-6">
    <img src="YOUR_IMAGE_URL_HERE/family-beach-shaded.webp" alt="Çocukla Plaj Keyfi" class="w-full h-auto rounded-lg shadow-md" />
</div>

<ul class="list-none space-y-2">
    <li>🟢 <strong>09:00–11:00:</strong> Deniz sakin, hava yumuşak, çocuk enerjik.</li>
    <li>🔴 <strong>11:00–16:00:</strong> Sıcak + güneş baskısı artar (gölge şart).</li>
    <li>🟡 <strong>16:00 sonrası:</strong> Rahat ama rüzgâr artabilir.</li>
</ul>

<hr class="my-8" />

<h2>Sıkça Sorulan Sorular</h2>

<div class="space-y-4">
    <details class="bg-gray-50 p-4 rounded-lg">
        <summary class="font-semibold cursor-pointer">Çocukla en güvenli “sığ deniz” hangi tip yerlerde olur?</summary>
        <p class="mt-2 text-gray-700">Lagün ve kapalı koy mantığındaki yerlerde su genelde daha sakin olur.</p>
    </details>
    <details class="bg-gray-50 p-4 rounded-lg">
        <summary class="font-semibold cursor-pointer">“Deniz hemen derinleşiyor mu?” sorusunu orada nasıl anlarsın?</summary>
        <p class="mt-2 text-gray-700">Kıyıdan 5–10 adım at: Dizden bel hizasına hızlı geliyorsa küçük çocuk için daha dikkatli ol.</p>
    </details>
    <details class="bg-gray-50 p-4 rounded-lg">
        <summary class="font-semibold cursor-pointer">Kum mu çakıl mı? Çocuk için hangisi daha iyi?</summary>
        <p class="mt-2 text-gray-700">Genelde ince kum çocukla daha konforlu. Çakıl varsa deniz ayakkabısı büyük rahatlık sağlar.</p>
    </details>
    <details class="bg-gray-50 p-4 rounded-lg">
        <summary class="font-semibold cursor-pointer">Rüzgâr ne zaman daha problem olur?</summary>
        <p class="mt-2 text-gray-700">Birçok yerde öğleden sonra rüzgâr artabilir. Çocukla en sakin zaman çoğu gün sabah olur.</p>
    </details>
</div>

<div class="mt-8 p-6 bg-green-50 rounded-xl text-center">
    <h3 class="text-xl font-bold text-green-800 mb-2">Sonuç: “Nöbet” Değil, Anı Biriktirme Tatili</h3>
    <p class="text-green-700">Fethiye çocuklara sadece denizi değil; doğayı, yürüyüşü, farklı manzaraları da tanıtabilen bir yer. Çantanı hazırla, güneş kremini sür, sabah erken çık. Gerisi zaten akıyor.</p>
</div>',
    'YOUR_IMAGE_URL_HERE/fethiye-family-cover.webp',
    'Fethiye',
    'Çocuklu aileler için Fethiye''de sığ deniz, rüzgarsız koylar ve güvenli tatil rehberi. Bebekle denize girilecek en iyi yerler ve ipuçları.',
    true,
    NOW(),
    NOW(),
    NOW()
);
